package modelo;
// Generated 27-oct-2017 21:41:44 by Hibernate Tools 3.5.0.Final

/**
 * GestionId generated by hbm2java
 */
public class GestionId implements java.io.Serializable {

	private String codpiezas;
	private String codproyecto;
	private String codproveedor;

	public GestionId() {
	}

	public GestionId(String codpiezas, String codproyecto, String codproveedor) {
		this.codpiezas = codpiezas;
		this.codproyecto = codproyecto;
		this.codproveedor = codproveedor;
	}

	public String getCodpiezas() {
		return this.codpiezas;
	}

	public void setCodpiezas(String codpiezas) {
		this.codpiezas = codpiezas;
	}

	public String getCodproyecto() {
		return this.codproyecto;
	}

	public void setCodproyecto(String codproyecto) {
		this.codproyecto = codproyecto;
	}

	public String getCodproveedor() {
		return this.codproveedor;
	}

	public void setCodproveedor(String codproveedor) {
		this.codproveedor = codproveedor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GestionId))
			return false;
		GestionId castOther = (GestionId) other;

		return ((this.getCodpiezas() == castOther.getCodpiezas()) || (this.getCodpiezas() != null
				&& castOther.getCodpiezas() != null && this.getCodpiezas().equals(castOther.getCodpiezas())))
				&& ((this.getCodproyecto() == castOther.getCodproyecto())
						|| (this.getCodproyecto() != null && castOther.getCodproyecto() != null
								&& this.getCodproyecto().equals(castOther.getCodproyecto())))
				&& ((this.getCodproveedor() == castOther.getCodproveedor())
						|| (this.getCodproveedor() != null && castOther.getCodproveedor() != null
								&& this.getCodproveedor().equals(castOther.getCodproveedor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodpiezas() == null ? 0 : this.getCodpiezas().hashCode());
		result = 37 * result + (getCodproyecto() == null ? 0 : this.getCodproyecto().hashCode());
		result = 37 * result + (getCodproveedor() == null ? 0 : this.getCodproveedor().hashCode());
		return result;
	}

}
