package modelo;
// Generated 27-oct-2017 21:41:44 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores implements java.io.Serializable {

	private String codigo;
	private String nombre;
	private String apellidos;
	private String direccion;
	private Set gestions = new HashSet(0);

	public Proveedores() {
	}

	public Proveedores(String codigo, String nombre, String apellidos, String direccion) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.direccion = direccion;
	}

	public Proveedores(String codigo, String nombre, String apellidos, String direccion, Set gestions) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.gestions = gestions;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Set getGestions() {
		return this.gestions;
	}

	public void setGestions(Set gestions) {
		this.gestions = gestions;
	}

}
